# ArgoCD Application: AOS Audit Service.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aos-audit-service
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: aos
spec:
  project: aos
  source:
    repoURL: https://github.com/michelbuki14/AFRICA-OPERATING-SYSTEM-AOS-.git
    targetRevision: main
    path: helm/aos-chart
    helm:
      valueFiles:
        - values/audit.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: aos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
