-- Migration: 009_demo_seed.sql
-- Purpose: deterministic local demo tenant + Workforce data.
--
-- This is intentionally local-demo data. Production deployments must not run
-- this migration against a real tenant. Every write is idempotent so a demo
-- reset is not required just to restart the services.

-- The Keycloak realm export claims these IDs for dev-admin.
INSERT INTO organizations (ulid, name, slug, status, tier)
VALUES (
    '01ARZ3NDEKTSV4RRFFQ69G5FAX',
    'AOS Demo Organization',
    'aos-demo-org',
    'active',
    'professional'
)
ON CONFLICT (ulid) DO NOTHING;

INSERT INTO tenants (ulid, org_id, name, slug, status, tier)
SELECT
    '01ARZ3NDEKTSV4RRFFQ69G5FAW',
    id,
    'AOS Demo Tenant',
    'aos-demo-tenant',
    'active',
    'professional'
FROM organizations
WHERE ulid = '01ARZ3NDEKTSV4RRFFQ69G5FAX'
ON CONFLICT (ulid) DO NOTHING;

-- Keep a local platform user row for FK/audit resolution. The Keycloak subject
-- is intentionally left nullable: the subject is generated by Keycloak at
-- import time and is not stable enough to hard-code into SQL.
INSERT INTO users (ulid, org_id, tenant_id, email, display_name, status)
SELECT
    '01ARZ3NDEKTSV4RRFFQ69G5FAY',
    o.id,
    t.id,
    'dev-admin@aos.local',
    'Dev Admin',
    'active'
FROM organizations o
JOIN tenants t ON t.org_id = o.id
WHERE o.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FAX'
ON CONFLICT (ulid) DO NOTHING;

-- One legal entity, office, department, position and team make every org
-- structure card useful on the first demo login.
INSERT INTO wf_legal_entities (ulid, tenant_id, org_id, name, registration_number, status)
SELECT
    '01ARZ3NDEKTSV4RRFFQ69G5FB0', t.id, o.id,
    'AOS Demo Holdings Ltd', 'AOS-DEMO-001', 'active'
FROM organizations o JOIN tenants t ON t.org_id = o.id
WHERE o.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FAX'
ON CONFLICT (ulid) DO NOTHING;

INSERT INTO wf_locations (ulid, tenant_id, org_id, legal_entity_id, name, code, timezone)
SELECT
    '01ARZ3NDEKTSV4RRFFQ69G5FB1', t.id, o.id, le.id,
    'Kinshasa Office', 'KIN-01', 'Africa/Kinshasa'
FROM organizations o
JOIN tenants t ON t.org_id = o.id
JOIN wf_legal_entities le ON le.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FB0'
WHERE o.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FAX'
ON CONFLICT (ulid) DO NOTHING;

INSERT INTO wf_departments (ulid, tenant_id, org_id, name, code, location_id)
SELECT
    '01ARZ3NDEKTSV4RRFFQ69G5FB2', t.id, o.id, 'Operations', 'OPS', l.id
FROM organizations o
JOIN tenants t ON t.org_id = o.id
JOIN wf_locations l ON l.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FB1'
WHERE o.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FAX'
ON CONFLICT (ulid) DO NOTHING;

INSERT INTO wf_positions (ulid, tenant_id, org_id, department_id, title, code, job_grade, employment_type)
SELECT
    '01ARZ3NDEKTSV4RRFFQ69G5FB3', t.id, o.id, d.id,
    'Operations Lead', 'OPS-LEAD', 'G6', 'permanent'
FROM organizations o
JOIN tenants t ON t.org_id = o.id
JOIN wf_departments d ON d.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FB2'
WHERE o.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FAX'
ON CONFLICT (ulid) DO NOTHING;

INSERT INTO wf_teams (ulid, tenant_id, org_id, department_id, name, code)
SELECT
    '01ARZ3NDEKTSV4RRFFQ69G5FB4', t.id, o.id, d.id, 'Core Operations', 'CORE-OPS'
FROM organizations o
JOIN tenants t ON t.org_id = o.id
JOIN wf_departments d ON d.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FB2'
WHERE o.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FAX'
ON CONFLICT (ulid) DO NOTHING;

INSERT INTO wf_employees (
    ulid, tenant_id, org_id, employee_number, legal_name, preferred_name,
    email, phone, status, hire_date, current_department_id,
    current_position_id, current_location_id
)
SELECT
    '01ARZ3NDEKTSV4RRFFQ69G5FB5', t.id, o.id, 'EMP-0001',
    'Amina Mukendi', 'Amina', 'amina.mukendi@aos.demo', '+243 800 000 001',
    'active', DATE '2026-01-15', d.id, p.id, l.id
FROM organizations o
JOIN tenants t ON t.org_id = o.id
JOIN wf_departments d ON d.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FB2'
JOIN wf_positions p ON p.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FB3'
JOIN wf_locations l ON l.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FB1'
WHERE o.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FAX'
ON CONFLICT (ulid) DO NOTHING;

INSERT INTO wf_employment_records (
    ulid, tenant_id, employee_id, position_id, department_id, location_id,
    employment_type, effective_date, change_reason
)
SELECT
    '01ARZ3NDEKTSV4RRFFQ69G5FB6', t.id, e.id, p.id, d.id, l.id,
    'permanent', DATE '2026-01-15', 'Initial demo employment record'
FROM tenants t
JOIN wf_employees e ON e.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FB5'
JOIN wf_positions p ON p.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FB3'
JOIN wf_departments d ON d.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FB2'
JOIN wf_locations l ON l.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FB1'
WHERE t.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FAW'
ON CONFLICT (ulid) DO NOTHING;

INSERT INTO wf_compensation_records (
    ulid, tenant_id, employee_id, gross_amount_minor, currency_id,
    frequency, effective_date, change_reason
)
SELECT
    '01ARZ3NDEKTSV4RRFFQ69G5FB7', t.id, e.id, 450000, c.id,
    'monthly', DATE '2026-01-15', 'Initial demo compensation'
FROM tenants t
JOIN wf_employees e ON e.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FB5'
JOIN currencies c ON c.code = 'USD'
WHERE t.ulid = '01ARZ3NDEKTSV4RRFFQ69G5FAW'
ON CONFLICT (ulid) DO NOTHING;
