//! Configuration management for AOS services.
//!
//! Uses Figment for multi-source configuration (files, environment variables, secrets).

use crate::{NexoraError, NexoraResult};
use figment::{
    providers::{Env, Format, Toml},
    Figment,
};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::time::Duration;

/// A secret string that is redacted in logs, debug output, and JSON.
///
/// Used for connection URLs and other secrets loaded from configuration. The
/// cleartext is only accessible through [`RedactedSecret::expose`], keeping
/// secrets out of structured log lines and serialized responses.
#[derive(Clone, Default, PartialEq, Eq)]
pub struct RedactedSecret(String);

impl RedactedSecret {
    /// Wrap a secret value.
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    /// Expose the cleartext value to the caller.
    pub fn expose(&self) -> &str {
        &self.0
    }

    /// Consume the wrapper, returning the cleartext value.
    pub fn into_inner(self) -> String {
        self.0
    }
}

impl std::fmt::Debug for RedactedSecret {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "RedactedSecret([REDACTED])")
    }
}

impl std::fmt::Display for RedactedSecret {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "[REDACTED]")
    }
}

impl Serialize for RedactedSecret {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str("[REDACTED]")
    }
}

impl<'de> Deserialize<'de> for RedactedSecret {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(Self(value))
    }
}

/// Root configuration structure loaded from TOML + environment.
#[derive(Debug, Clone, Default, Deserialize, Serialize)]
pub struct Config {
    #[serde(default)]
    pub service: ServiceConfig,
    #[serde(default)]
    pub server: ServerConfig,
    #[serde(default)]
    pub database: DatabaseConfig,
    #[serde(default)]
    pub redis: RedisConfig,
    #[serde(default)]
    pub auth: AuthConfig,
    #[serde(default)]
    pub tracing: TracingConfig,
    #[serde(default)]
    pub s3: S3Config,
    #[serde(default)]
    pub gateway: GatewayConfig,
    #[serde(default)]
    pub audit: AuditConfig,
    #[serde(default)]
    pub features: HashMap<String, bool>,
}

/// S3-compatible object storage configuration (MinIO in dev, AWS S3 in prod).
///
/// Documents are NEVER publicly accessible: all GET access goes through a
/// short-lived presigned URL generated by the workforce service after RBAC
/// and IDOR checks pass. The bucket must be created with no public policy.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct S3Config {
    #[serde(default)]
    pub endpoint: String,
    #[serde(default)]
    pub region: String,
    #[serde(default)]
    pub bucket: String,
    #[serde(default)]
    pub access_key_id: RedactedSecret,
    #[serde(default)]
    pub secret_access_key: RedactedSecret,
    /// Presigned URL TTL in seconds. Keep short — 60s is the default.
    #[serde(default = "default_presign_ttl_secs")]
    pub presign_ttl_secs: u64,
    /// Use path-style addressing (required for MinIO; AWS prefers virtual-hosted).
    #[serde(default)]
    pub force_path_style: bool,
}

impl Default for S3Config {
    fn default() -> Self {
        Self {
            endpoint: "http://localhost:9000".to_string(),
            region: "us-east-1".to_string(),
            bucket: "nexora-workforce-documents".to_string(),
            access_key_id: RedactedSecret::new("minioadmin"),
            secret_access_key: RedactedSecret::new("minioadmin"),
            presign_ttl_secs: 60,
            force_path_style: true,
        }
    }
}

/// Service identification and metadata.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ServiceConfig {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub version: String,
    #[serde(default)]
    pub environment: Environment,
    /// Auto-generated per-process ULID; omit from config files.
    #[serde(default = "crate::ulid::new_ulid")]
    pub instance_id: String,
}

impl Default for ServiceConfig {
    fn default() -> Self {
        Self {
            name: "nexora-service".to_string(),
            version: env!("CARGO_PKG_VERSION").to_string(),
            environment: Environment::Development,
            instance_id: crate::ulid::new_ulid(),
        }
    }
}

/// Deployment environment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum Environment {
    #[default]
    Development,
    Staging,
    Production,
}

impl Environment {
    pub fn is_production(&self) -> bool {
        matches!(self, Environment::Production)
    }
}

/// HTTP server configuration.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ServerConfig {
    #[serde(default = "default_server_host")]
    pub host: String,
    #[serde(default = "default_server_port")]
    pub port: u16,
    #[serde(default)]
    pub workers: Option<usize>,
    #[serde(default = "default_request_timeout_secs")]
    pub request_timeout_secs: u64,
    #[serde(default = "default_body_limit_bytes")]
    pub body_limit_bytes: usize,
    #[serde(default = "default_graceful_shutdown_secs")]
    pub graceful_shutdown_secs: u64,
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            host: "0.0.0.0".to_string(),
            port: 3000,
            workers: None,
            request_timeout_secs: 30,
            body_limit_bytes: 10 * 1024 * 1024,
            graceful_shutdown_secs: 30,
        }
    }
}

/// Database connection configuration.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct DatabaseConfig {
    #[serde(default)]
    pub url: RedactedSecret,
    #[serde(default = "default_max_connections")]
    pub max_connections: u32,
    #[serde(default = "default_min_connections")]
    pub min_connections: u32,
    #[serde(default = "default_connect_timeout_secs")]
    pub connect_timeout_secs: u64,
    #[serde(default = "default_idle_timeout_secs")]
    pub idle_timeout_secs: u64,
    #[serde(default = "default_max_lifetime_secs")]
    pub max_lifetime_secs: u64,
    #[serde(default)]
    pub enable_logging: bool,
}

impl Default for DatabaseConfig {
    fn default() -> Self {
        Self {
            url: RedactedSecret::new("postgres://nexora:nexora_dev_password@localhost:5432/nexora"),
            max_connections: 20,
            min_connections: 5,
            connect_timeout_secs: 10,
            idle_timeout_secs: 300,
            max_lifetime_secs: 1800,
            enable_logging: false,
        }
    }
}

/// Redis configuration.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct RedisConfig {
    #[serde(default)]
    pub url: RedactedSecret,
    #[serde(default = "default_redis_max_connections")]
    pub max_connections: u32,
    #[serde(default = "default_redis_connection_timeout_secs")]
    pub connection_timeout_secs: u64,
    #[serde(default = "default_redis_command_timeout_secs")]
    pub command_timeout_secs: u64,
}

impl Default for RedisConfig {
    fn default() -> Self {
        Self {
            url: RedactedSecret::new("redis://:nexora_dev_password@localhost:6379/0"),
            max_connections: 50,
            connection_timeout_secs: 5,
            command_timeout_secs: 5,
        }
    }
}

/// Authentication and authorization configuration.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct AuthConfig {
    #[serde(default)]
    pub jwks_url: String,
    #[serde(default)]
    pub issuer: String,
    #[serde(default)]
    pub audience: String,
    #[serde(default = "default_jwks_cache_ttl_secs")]
    pub jwks_cache_ttl_secs: u64,
    #[serde(default)]
    pub require_https: bool,
    #[serde(default)]
    pub allowed_algorithms: Vec<String>,
}

impl Default for AuthConfig {
    fn default() -> Self {
        Self {
            jwks_url: "http://localhost:8080/realms/nexora/protocol/openid-connect/certs"
                .to_string(),
            issuer: "http://localhost:8080/realms/nexora".to_string(),
            audience: "nexora-api".to_string(),
            jwks_cache_ttl_secs: 300,
            require_https: false,
            allowed_algorithms: vec!["RS256".to_string()],
        }
    }
}

/// OpenTelemetry tracing configuration.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct TracingConfig {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub otlp_endpoint: String,
    #[serde(default)]
    pub service_name: String,
    #[serde(default = "default_sample_rate")]
    pub sample_rate: f64,
    #[serde(default = "default_export_timeout_secs")]
    pub export_timeout_secs: u64,
}

impl Default for TracingConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            otlp_endpoint: "http://localhost:4317".to_string(),
            service_name: "nexora-service".to_string(),
            sample_rate: 1.0,
            export_timeout_secs: 10,
        }
    }
}

/// Audit service configuration.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct AuditConfig {
    /// Signing secret for HMAC hash chain. In production, this should be
    /// loaded from a vault/HSM. Minimum 32 bytes for HMAC-SHA-256.
    #[serde(default)]
    pub signing_secret: RedactedSecret,
}

impl Default for AuditConfig {
    fn default() -> Self {
        Self {
            // Dev default - in production, MUST be overridden via NEXORA_AUDIT__SIGNING_SECRET
            signing_secret: RedactedSecret::new("dev-audit-signing-secret-min-32-bytes-long!!"),
        }
    }
}

/// Gateway proxy configuration for upstream service URLs.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct GatewayConfig {
    #[serde(default)]
    pub workforce_base_url: String,
    #[serde(default)]
    pub audit_base_url: String,
    #[serde(default)]
    pub tenant_base_url: String,
    #[serde(default)]
    pub fintech_base_url: String,
    #[serde(default)]
    pub retail_base_url: String,
    #[serde(default)]
    pub gov_base_url: String,
    #[serde(default)]
    pub payroll_base_url: String,
}

impl Default for GatewayConfig {
    fn default() -> Self {
        Self {
            workforce_base_url: "http://localhost:3001".to_string(),
            audit_base_url: "http://localhost:3002".to_string(),
            tenant_base_url: "http://localhost:3003".to_string(),
            fintech_base_url: "http://localhost:3005".to_string(),
            retail_base_url: "http://localhost:3006".to_string(),
            gov_base_url: "http://localhost:3007".to_string(),
            payroll_base_url: "http://localhost:3008".to_string(),
        }
    }
}

impl Config {
    /// Load configuration from file and environment.
    /// Priority: defaults < config.toml < environment variables < secrets
    pub fn load() -> NexoraResult<Self> {
        let env = std::env::var("NEXORA_ENV").unwrap_or_else(|_| "development".to_string());
        let config_file = format!("config.{env}.toml");

        let figment = Figment::new()
            .merge(Toml::file(&config_file))
            .merge(Env::prefixed("NEXORA_").split("__"));

        figment
            .extract()
            .map_err(|e| NexoraError::Config(e.to_string()))
    }

    /// Get the database URL as a plain string (for sqlx).
    pub fn database_url(&self) -> String {
        self.database.url.expose().to_string()
    }

    /// Get the Redis URL as a plain string.
    pub fn redis_url(&self) -> String {
        self.redis.url.expose().to_string()
    }

    /// Check if a feature flag is enabled.
    pub fn is_feature_enabled(&self, feature: &str) -> bool {
        self.features.get(feature).copied().unwrap_or(false)
    }
}

/// Convert Duration to human-readable string.
pub fn duration_to_string(d: Duration) -> String {
    if d.as_secs() >= 86400 {
        format!("{}d", d.as_secs() / 86400)
    } else if d.as_secs() >= 3600 {
        format!("{}h", d.as_secs() / 3600)
    } else if d.as_secs() >= 60 {
        format!("{}m", d.as_secs() / 60)
    } else {
        format!("{}s", d.as_secs())
    }
}


// Field-level defaults used by `#[serde(default = "...")]` so that partial
// environment overrides (e.g. `NEXORA_DATABASE__URL` alone) merge with the
// real non-zero defaults instead of `FieldType::default()` (which is 0 for u32).
pub fn default_max_connections() -> u32 { 20 }
pub fn default_min_connections() -> u32 { 5 }
pub fn default_connect_timeout_secs() -> u64 { 10 }
pub fn default_idle_timeout_secs() -> u64 { 300 }
pub fn default_max_lifetime_secs() -> u64 { 1800 }
pub fn default_server_host() -> String { "0.0.0.0".to_string() }
pub fn default_server_port() -> u16 { 3000 }
pub fn default_request_timeout_secs() -> u64 { 30 }
pub fn default_body_limit_bytes() -> usize { 10 * 1024 * 1024 }
pub fn default_graceful_shutdown_secs() -> u64 { 30 }
pub fn default_redis_max_connections() -> u32 { 50 }
pub fn default_redis_connection_timeout_secs() -> u64 { 5 }
pub fn default_redis_command_timeout_secs() -> u64 { 5 }
pub fn default_jwks_cache_ttl_secs() -> u64 { 300 }
pub fn default_sample_rate() -> f64 { 1.0 }
pub fn default_export_timeout_secs() -> u64 { 10 }
pub fn default_presign_ttl_secs() -> u64 { 60 }
