apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexora.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexora.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "nexora.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
